[Improve code]: src/utils/*.ts 手動formatter・Linter対応
nekono-dev/skyshare pull request #78
Opened 2024-04-06 08:56 UTC by ZEKE320

Resolves #63

2024-04-06 09:29 UTC, ZEKE320 commented
下記のマージ有無が確定次第、ドラフト状態を解除します。
- #79

2024-04-07 07:19 UTC, ZEKE320 commented
Zodの変更をマージしました
レビューお願いします

2024-04-08 02:53 UTC, nkte8 requested changes
対応ありがとうございます！確認しました。ちょっと実装イメージにずれがあったのでコメントをしています、ご確認ください

2024-04-08 02:53 UTC, nkte8 commented on astro/src/utils/useLocalStorage.ts
> +const SavedDrafts = z.array(z.string())
`Zod`のオブジェクトであることを明示する分で、`ZodSavedTags`といった具合に、Zodを冠詞に付けるのがいいかなと思っています。

2024-04-08 02:53 UTC, nkte8 commented on astro/src/utils/useLocalStorage.ts
>  export const readDrafts = (): Array<string> => {
こちらも`LoginInfo`で採用している方法と同様に、（冗長ではありますが）`type SavedDrafts = z.infer<typeof ZodSavedDrafts>`を定義して、これを返り値にするのがいいと思います。

2024-04-08 02:53 UTC, nkte8 commented on astro/src/utils/useLocalStorage.ts
>  export const saveDrafts = (Drafts: string[]): void => {
`SavedTags`と同様に、`type SavedDrafts = z.infer<typeof ZodSavedDrafts>`の定義内容を使うのがいいのかと思います。

2024-04-08 02:53 UTC, nkte8 commented on astro/src/utils/useLocalStorage.ts
>  export const readSavedTags = (): Array<string> => {
LoginInfoで採用している方法と同様に`type SavedTags = z.infer<typeof ZodSavedTags>`を定義して、これを返り値の型にするのがいいかと。

2024-04-08 02:53 UTC, nkte8 commented on astro/src/utils/useLocalStorage.ts
>  export const setSavedTags = (Tags: string[]): void => {
入力の引数にも`type SavedDrafts = z.infer<typeof ZodSavedTags>`を定義してこれを使うのがいいのかと。型の内容自体は変わらないはずなので他コードに干渉することもないと思います。

2024-04-08 02:53 UTC, nkte8 commented on astro/src/utils/useLocalStorage.ts
> +import { z } from "zod"
#79 で気づけずすみません。`packages-lock.json`にはzodのインストールは記載されているのですが、あくまで他パッケージ依存のような形になってしまっているので、`packages.json`にzodが必要であることを明示したいです。インストール処理をお願いします。

2024-04-11 16:08 UTC, ZEKE320 commented on astro/src/utils/useLocalStorage.ts
> +const SavedDrafts = z.array(z.string())
対応しました！

2024-04-11 16:08 UTC, ZEKE320 commented on astro/src/utils/useLocalStorage.ts
>  export const readDrafts = (): Array<string> => {
対応しました！

2024-04-11 16:08 UTC, ZEKE320 commented on astro/src/utils/useLocalStorage.ts
>  export const saveDrafts = (Drafts: string[]): void => {
対応しました！

2024-04-11 16:08 UTC, ZEKE320 commented on astro/src/utils/useLocalStorage.ts
>  export const readSavedTags = (): Array<string> => {
対応しました！

2024-04-11 16:08 UTC, ZEKE320 commented on astro/src/utils/useLocalStorage.ts
>  export const setSavedTags = (Tags: string[]): void => {
対応しました！

2024-04-11 16:09 UTC, ZEKE320 commented on astro/src/utils/useLocalStorage.ts
> +import { z } from "zod"
本当ですね
改めて対応しました

2024-04-11 16:10 UTC, ZEKE320 commented
@nkte8 
フィードバック対応しました
改めて、レビューをお願いします

2024-04-12 14:38 UTC, nkte8 approved these changes
対応ありがとうございました！マージします！

2024-04-12 14:38 UTC, merged