[Improve code]: astro/src/components/Client/bsky/* 手動formatter・Linter対応
nekono-dev/skyshare pull request #83
Opened 2024-04-07 08:42 UTC by ZEKE320

Resolves #55

2024-04-08 13:19 UTC, nkte8 requested changes
対応ありがとうございます！コメント箇所について、確認お願いします。

`models/*.json`に関する問題、json importで利用できる型定義は厳密ではないので使うべきではない問題についてはformatter/linter対応ではスルーします（別途Issue立てます）

2024-04-08 13:19 UTC, nekono-dev commented on astro/src/components/Client/bsky/LoginForm.tsx
> +                                （BskyLinXに限らず）非公式のアプリを使う際はAppPasswordの利用が推奨されています。
作業対象範囲外の修正で失礼します。旧App名になってしまっているので、この値を`src/env/vars.ts`の`servicename`変数を参照するように修正していただきたいです。恐縮です、よろしくお願いいたします。

2024-04-08 13:19 UTC, nkte8 commented on astro/src/components/Client/bsky/buttons/PostButton.tsx
> +                    resultUploadBlob as uploadBlobSuccessResult[]
コメントでエラーがスローされなかった場合はresultUploadBlobが必ずSuccessResultになるのを書いていただけると助かります

2024-04-08 13:19 UTC, nekono-dev commented on astro/src/components/Client/bsky/buttons/PostButton.tsx
> +                    if ("error" in value && typeof value.error != "undefined") {
この箇所 ` value.error != "undefined"` が厳格な比較じゃなくなったのって何か理由がありますでしょうか。
（そもそも`in`で判定してるから要らない可能性はありえますが...）

2024-04-08 13:19 UTC, nekono-dev commented on astro/src/components/Client/bsky/buttons/PostButton.tsx
> +                typeof createRecordResult.error != "undefined"
こちらも、`typeof`の判定が厳格な比較じゃなくなったのって何か理由がありますでしょうか。
（そもそもinで判定してるから要らない可能性はありえますが...）

2024-04-08 13:19 UTC, nekono-dev commented on astro/src/components/Client/bsky/lib/loadProfile.ts
> +        if (res != null && !("error" in res)) {
`res`の判定が厳格な比較じゃなくなったのって何か理由がありますでしょうか。

2024-04-08 13:19 UTC, nekono-dev commented on astro/src/components/Client/bsky/unique/LoadSession.tsx
> +                    typeof refreshResult.error != "undefined"
`typeof`の判定が厳格な比較じゃなくなったのって何か理由がありますでしょうか。
（そもそもinで判定してるから要らない可能性はありえますが...）

2024-04-08 13:19 UTC, nekono-dev commented on astro/src/components/Client/bsky/unique/TextInputBox.tsx
> +        } catch (_e) {
これって変数名を`_`にするとエラーする感じでしょうか。
特に使われない変数なら名前を付ける必要もないのかなと思いました。

2024-04-10 14:10 UTC, ZEKE320 commented on astro/src/components/Client/bsky/buttons/PostButton.tsx
> +                    if ("error" in value && typeof value.error != "undefined") {
レビューありがとうございます！

理由としては次の2つでしょうか
1. JSONの定義には`undefined`を用いることが出来ず、atproto APIの戻り値としては`null`が入り得るため
1. 現状では、レスポンスの型定義が`typeof JSON`のため、`undefined` `null`の両方が入りうることを見据えて

ただし、TypeScript側で型定義をしている場合であれば、厳密等価演算子`===` `!==`を用いる方針で統一したほうが良いかもしれませんね...
関係のない箇所も等価演算子(`==` `!=`)に書き直してしまった気がするので、そちらに関しては後々、元のコードに修正します。

---

また質問なのですが、`"error" in value`のみの形式でエラー型判定をする方針で統一してしまっても問題ありませんか？
そうすると、その後の成功レスポンスを`as MyType`の形式でアサーションする必要がなく、後々の修正がしやすくなると思います
（`val as MyType`や`<MyType>val`で型アサーションした変数は、実際の型に関わらずその型として見做されてしまうので、可能であれば減らしたいな。と考えています）

2024-04-10 14:51 UTC, ZEKE320 commented on astro/src/components/Client/bsky/LoginForm.tsx
> +                                （BskyLinXに限らず）非公式のアプリを使う際はAppPasswordの利用が推奨されています。
対応済みです！

2024-04-10 14:51 UTC, ZEKE320 commented on astro/src/components/Client/bsky/buttons/PostButton.tsx
> +                    resultUploadBlob as uploadBlobSuccessResult[]
対応しました！

2024-04-10 14:51 UTC, ZEKE320 commented on astro/src/components/Client/bsky/unique/TextInputBox.tsx
> +        } catch (_e) {
対応しました！

2024-04-10 15:28 UTC, nkte8 commented on astro/src/components/Client/bsky/buttons/PostButton.tsx
> +                    if ("error" in value && typeof value.error != "undefined") {
@ZEKE320 
説明・根拠等の提示ありがとうございます！
1. これは確かにありそうですね。レスポンスとして定義されていない変数が返された際に`null`と`undefined`どちらになるのかわからない問題。一方、現状のAtprotoの仕様においてはエラーの場合は[必ず`error,message`を返すようになっているため、この懸念が必要ないのではないか、とも思っています(https://atproto.com/specs/xrpc#error-responses)](https://atproto.com/specs/xrpc#error-responses)。
2. `typeof JSON`のところはおっしゃる通りですね（そのままでいいと思いました）
    `typeof JSON`ではない箇所については気にする必要ないかなと思いました（現在仕様が入り乱れてしまっているので恐縮ですが..）

> ただし、TypeScript側で型定義をしている場合であれば、厳密等価演算子=== !==を用いる方針で統一したほうが良いかもしれませんね...

そうですね。`typeof JSON`についてはすべて削除したいと思っていて (#88 )、厳密透過演算子で統一したいという気持ちがあります。`atproto_api`については #15 の仕様によっては、判定処理も必要ないかもしれませんが...（調査中です）

> また質問なのですが、"error" in valueのみの形式で、エラー型を判定する方針で統一しても問題ないでしょうか？
そのようにした場合、その後の成功レスポンスをas MyTypeの形式でアサーションする必要がなく、後々の修正が楽になるかと思います
（val as MyTypeや<MyType>valで型アサーションした変数は、実際の型に関わらず、アサーションした型として見做されてしまうので、可能であれば減らしたい。という考えです）

私は現状のATProtoの仕様状況も踏まえて、`error`がResponseに帰ってくるのはエラーの時だけである、という前提があるので`"error" in valueのみの形式で、エラー型を判定する`でいいと思っていますが、上で提示していただいた(1)(2)以外にも懸念事項ある感じでしょうか（良ければ教えていただければ幸いです🙇）

2024-04-10 16:08 UTC, ZEKE320 commented on astro/src/components/Client/bsky/buttons/PostButton.tsx
> +                    if ("error" in value && typeof value.error != "undefined") {
@nkte8 
返信ありがとうございます！このほか特に問題はありません

確認となりますが、

1. `エラーを意味する特定のキー(errorなど)`を含むユニオン型は、そのキーの有無(`"キー名" in response`)のみで型判定する。（このとき、特定のキーが存在した時点でエラーとみなし、値の型については確認しない）
3. 1により、`ESLint` `TypeScript`ではユニオン型に関するエラーが解消するため、
    今回のPRで追加された`型アサーション付き変数` (`val as Type`や`<Type> val`)は削除する。
4. 変数に明確な型定義が存在する場合、`undefined` `null`に対しても厳密等価演算子(`===`, `!==`)を用いて型判定を行う

という方針で問題ありませんか？

---
> 一方、現状のAtprotoの仕様においてはエラーの場合は[必ずerror,messageを返すようになっているため、この懸念が必要ないのではないか、とも思っています(https://atproto.com/specs/xrpc#error-responses)](https://atproto.com/specs/xrpc#error-responses)。

atprotoの仕様共有ありがとうございます！

余談ですが、

> JSONの定義[1](https://github.com/nkte8/skyshare/pull/83#user-content-fn-1-21671ad4578b6bfe00cc1dd809e4c496)には`null`型が存在し、atproto APIのレスポンスとしてnullが入り得るため

そもそも`{"error": null}`のような謎レスポンスを返すとは考えにくいので、`null`型のケースあまり考えなくても良いかもしれませんね笑
もちろん、`"error" in value`のみで判定する方針であれば、この点については心配ないと思います

2024-04-10 16:24 UTC, nekono-dev commented on astro/src/components/Client/bsky/buttons/PostButton.tsx
> +                    if ("error" in value && typeof value.error != "undefined") {
@ZEKE320 方針の整理ありがとうございます！認識合います。 #84 https://github.com/nkte8/skyshare/pull/84#issuecomment-2047756599 の方も基本的に同じ方針でOKです、PRの方に細かいこと書いておきます。

2024-04-11 07:10 UTC, nkte8 commented
（@ZEKE320  対応終わりましたら Re-request review を押していただけると判断付くのでお願いします！ ）

2024-04-11 10:22 UTC, ZEKE320 commented
@nkte8 
おそらくすべて対応完了したと思います
あらためて、レビューをお願いします

2024-04-11 11:33 UTC, nkte8 approved these changes
対応箇所多い中ありがとうございました！マージします

2024-04-11 11:33 UTC, merged