[Improve code]: lib/* 手動formatter・Linter対応
nekono-dev/skyshare pull request #84
Opened 2024-04-07 14:00 UTC by ZEKE320

Resolves #58

2024-04-07 14:16 UTC, ZEKE320 commented
ひとまず`ESLint`のエラーを解消し終わりました
レビューをお願いします！

2024-04-08 12:41 UTC, nkte8 requested changes
対応ありがとうございます！確認・必要に応じて対応お願いします。

エラーの出し方（エラーハンドリングの際に返却する`e.name`と`e.description`の値）については明確にどうするかをまだ決めていなかったので、いったんはこのままにしておきます。

2024-04-08 12:41 UTC, nekono-dev commented on astro/src/lib/pagedbAPI/createPage.ts
> +})
Zodの対応ありがとうございます！ #79 では`Zod`は冠詞的にくっつけていたのが、こちらでは接尾についているようです。こちらは #79 とは違った意図がある感じでしょうか？
（理由がないのであればどちらかに統一した方がいいのかなと @nkte8 は思っている感じです。）

2024-04-08 12:41 UTC, nekono-dev commented on astro/src/lib/api/types.ts
全体のZodオブジェクトについて、https://github.com/nkte8/skyshare/pull/79 ではZodは冠詞的にくっつけていたのが、こちらでは接尾についているようです。こちらは https://github.com/nkte8/skyshare/pull/79 とは違った意図がある感じでしょうか？
（理由がないのであればどちらかに統一した方がいいのかなと @nkte8 は思っている感じです。）

2024-04-08 12:41 UTC, nkte8 commented on astro/src/pages/api/getOgpMeta.ts
> +            html: responseHTML,
一時期テストに使っていたコードが残ってしまっていたみたいです...
`html: string`の戻り値を消していただきたいです。作業範囲的に対象外なので恐縮ですが、よろしくお願いいたします。

2024-04-08 12:41 UTC, nkte8 commented on astro/src/lib/pagedbAPI/deletePage.ts
#79 では`Zod`は冠詞的にくっつけていたのが、こちらでは接尾についているようです。こちらは #79 とは違った意図がある感じでしょうか？
（理由がないのであればどちらかに統一した方がいいのかなと @nkte8 は思っている感じです。）

2024-04-08 12:41 UTC, nkte8 commented on astro/src/lib/pagedbAPI/getIds.ts
リネーム対応ありがとうございます！気づきませんでした...

#79 では`Zod`は冠詞的にくっつけていたのが、こちらでは接尾についているようです。こちらは #79 とは違った意図がある感じでしょうか？
（理由がないのであればどちらかに統一した方がいいのかなと @nkte8 は思っている感じです。）

2024-04-08 12:41 UTC, nkte8 commented on astro/src/lib/pagedbAPI/getPage.ts
#79 では`Zod`は冠詞的にくっつけていたのが、こちらでは接尾についているようです。こちらは #79 とは違った意図がある感じでしょうか？
（理由がないのであればどちらかに統一した方がいいのかなと @nkte8 は思っている感じです。）

2024-04-08 12:41 UTC, nkte8 commented on astro/src/lib/pagedbAPI/models/db.json
getPage.tsの方に埋め込む形になったと思うので、消してしまいましょうか。

2024-04-08 12:41 UTC, nkte8 commented on astro/src/pages/posts/[slug].astro
> +if ("error" in getPageResult && typeof getPageResult?.error !== "undefined" && getPageResult.error !== "") {
作業範囲的に対象外の修正なので恐縮です。getPageAPIはskyshare定義のAPIなので、戻り型の検証は型特定部分だけで良いと思いました。`getPage.ts`を見る限り、エラーの場合は必ず`error`と`message`を持つレスポンスを行うためです。
なので条件式は`("error" in getPageResult)`でもいいかもと思っています、ご意見伺いたいです。

（*`(typeof getpage_res?.error !== "undefined" && getpage_res.error !== "")`という回りくどい書き方をしていたのは、原本を作成した @nkte8 が`in`演算子を知らなかったためです...*）

2024-04-10 13:03 UTC, ZEKE320 commented on astro/src/lib/pagedbAPI/createPage.ts
> +})
気づいていませんでした... `Zod接頭辞 + [型名]`で統一しておきますね

2024-04-10 13:04 UTC, ZEKE320 commented on astro/src/lib/api/types.ts
- https://github.com/nkte8/skyshare/pull/84#discussion_r1559397768
上記同様対応しました。

2024-04-10 13:05 UTC, ZEKE320 commented on astro/src/pages/api/getOgpMeta.ts
> +            html: responseHTML,
対応しました！

2024-04-10 13:05 UTC, ZEKE320 commented on astro/src/lib/pagedbAPI/deletePage.ts
- https://github.com/nkte8/skyshare/pull/84#discussion_r1559397768
上記同様対応しました。

2024-04-10 13:05 UTC, ZEKE320 commented on astro/src/lib/pagedbAPI/getIds.ts
- https://github.com/nkte8/skyshare/pull/84#discussion_r1559397768
上記同様対応しました。

2024-04-10 13:05 UTC, ZEKE320 commented on astro/src/lib/pagedbAPI/getPage.ts
- https://github.com/nkte8/skyshare/pull/84#discussion_r1559397768
上記同様対応しました。

2024-04-10 13:06 UTC, ZEKE320 commented on astro/src/lib/pagedbAPI/models/db.json
対応しました！

2024-04-10 13:06 UTC, ZEKE320 commented on astro/src/pages/posts/[slug].astro
> +if ("error" in getPageResult && typeof getPageResult?.error !== "undefined" && getPageResult.error !== "") {
了解です！
対応しました

2024-04-10 13:12 UTC, ZEKE320 commented
- https://github.com/nkte8/skyshare/pull/84/commits/967b3278408780d935a0f1d8ffa5578e7a594f6f Zodオブジェクト命名規則の統一 
- https://github.com/nkte8/skyshare/pull/84/commits/4fd4e58ebfa102f12ab4c87186897d55d9a7d22e `getOgpMeta`のエラーレスポンスから`html`を削除 
- https://github.com/nkte8/skyshare/pull/84/commits/ce937a78725085128e574cbfd463ea6b26e7aae5 使用されていないレスポンス型定義用のJSONを削除 
- https://github.com/nkte8/skyshare/pull/84/commits/0fc4c2d63d9c484a544fee9a5ca02badc3fed685 `pages/post/[slug].astro`エラー型判定の実装を改善 

上記4点対応済みです。確認をお願いします！

2024-04-10 14:45 UTC, ZEKE320 commented
@nkte8 
今のタイミングで、エラーの型判定箇所を統一しておきたいですね
- https://github.com/nkte8/skyshare/pull/83#discussion_r1559518736

こちらで一度、方針を伝えていただけるとありがたいです！

2024-04-10 16:30 UTC, nkte8 commented
@ZEKE320 
> エラーの型判定箇所を統一しておきたいですね

上について、https://github.com/nkte8/skyshare/pull/83#discussion_r1559757051 での議論通り、`error in value`での判定に揃えていただいてOKです。以下コメントです

- getOgpMeta関数については、ATProtoでのエラー時のレスポンスを同じような形式、`error,message`で返すようにしているので、これと同じ方針を取っていただいて大丈夫です！
  - 現在は`type`によりユニオン型として処理可能なようにしていますが、この方法でパラメータを外せそうですね。これは別途Issueを上げときます
- `getOgpBlob`についても、現在はレスポンス自体発生しない作りになってしまっていますが、`error in value`の判定によって、クライアント側でエラーハンドリングができそうな気がしますね
  - 上と同じ題目でIssue上げようと思います。

2024-04-11 15:38 UTC, ZEKE320 commented
@nkte8 
- https://github.com/nkte8/skyshare/pull/84#issuecomment-2048001547
> getOgpMeta関数については、ATProtoでのエラー時のレスポンスを同じような形式、error,messageで返すようにしているので、これと同じ方針を取っていただいて大丈夫です！

こちらの件ですが、あまり良い実装例が思い浮かばず...すみません。
一度別のIssueでお願いしたいと思います。

--- 
@nkte8 
また上記とは別で、実装方針を伺いたい点があり
```tsx
// PageDeleteButton.tsx(32行目)

if (!("error" in resDeletePage) &&
    resDeletePage.result === "ok") {
  /* ... */
} else {
  let e: Error = new Error((resDeletePage as typeof etype).message)
  /* ... */
}
```
ここで条件式を`if (!("error" in resDeletePage))`とした場合、`resDeletePage as typeof etype`の型アノテーションを削除できるのですが、おそらく`resDeletePage.result === "ok"`も判定したいということですよね

1. `"error"`が`resDeletePage`のキーに含まれる場合 
    → エラー（原因A）をスロー
2. `"error"`が`resDeletePage`のキーには含まれないが、`resDeletePage.result`が`"ok"`ではない場合 
    → エラー（原因B）をスロー
3. `"error"`が`resDeletePage`のキーに含まれず、`resDeletePage.result`が`"ok"`の場合 
    → 処理を続行

の３つで場合分けをする方針で進めましょうか？

2024-04-11 15:51 UTC, nkte8 commented
@ZEKE 確認ありがとうございます！
> こちらの件ですが、あまり良い実装例が思い浮かばず...すみません。
一度別のIssueでお願いしたいと思います。

承知です！

> ここで条件式をif (!("error" in resDeletePage))とした場合、resDeletePage as typeof etypeの型アノテーションを削除できるのですが、おそらくresDeletePage.result === "ok"も判定したいということですよね

ここなんですけど、そもそも元の処理が以下のようになっています。
`firebase/functions/src/editDbEndpoint/entrypoint.prod.ts`
```
...
        if (resPagedbdel === null) {
            response.status(500).send(errRes(500))
            return
        }
        if (typeof resPagedbdel.result === "undefined") {
            response.status(502).send(errRes(502))
            return
        }
        // 正常に削除完了
        response.status(200).send({
            result: "ok"
        });
        // OGPを削除
        const ogpFilename = `${handleFromId}/${rkeyFromId}`
        await deleteOgp({
            env: envName,
            ogpFilename: ogpFilename
        })
        response.end();
```
このAPIだいぶ昔に書いたのですが、多分レスポンス自体に意味はなさそうなんですよね...エラーが発生しなかった場合は必ずresponse 200で、`{ result: ok }`が返却され、それ以外の200レスポンスは無い感じです。
現在のコードでは`error`の判定方法が曖昧だったから念の為条件を書いた、というように見えています。過去の自分ならやりそう。

ので、`resDeletePage.result`の判定は消しちゃっていいです。おおもとのこのAPIも改善しようと思います。

2024-04-11 16:32 UTC, ZEKE320 commented
@nkte8 返信ありがとうございます！
対応行いましたので、再度レビューをお願いします

2024-04-12 14:45 UTC, nkte8 approved these changes
対応ありがとうございました！マージします

2024-04-12 14:45 UTC, merged